#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Maps the user's 1500-feature list onto what this repository actually contains.

Every status below is asserted against code I read in this session, not from memory of
what a design tool usually has. Where the model carries a capability but nothing on
screen reaches it, the status is HALF rather than DONE — that distinction is the whole
point of the exercise.
"""
import collections, os, re, sys

# Both relative to the repository root, so the audit can be regenerated from a fresh clone. They
# used to be absolute paths into a scratch directory and an uploads folder, neither of which
# outlives a session — which made a 1600-line document nobody could reproduce or correct.
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(HERE, "features-1500.txt")
OUT = os.path.join(ROOT, "docs", "FEATURE-AUDIT-1500.md")

DONE, HALF, MISSING, OUT_OF_SCOPE = "✅", "🟡", "❌", "⛔"

# Rules applied in order; a later rule wins. A rule is (numbers, status, note).
RULES = []
def rule(nums, status, note):
    if isinstance(nums, int):
        nums = [nums]
    elif isinstance(nums, tuple):
        nums = range(nums[0], nums[1] + 1)
    RULES.append((list(nums), status, note))

# ─────────────────────────────────────────────── section 1: Photoshop, 1–250
rule((1, 250), MISSING, "")
rule([1, 2], OUT_OF_SCOPE, "مولد تصویر با مدل ابری — خارج از قید «بدون هوش مصنوعی، آفلاین»")
rule([3, 4, 5], HALF, "موتورش هست (PatchMatch) و روی انتخاب کار می‌کند؛ نسخهٔ قلم‌مویی ندارد")
rule(6, HALF, "ترمیم روی انتخاب هست؛ کشیدن انتخاب روی ناحیهٔ منبع نیست")
rule(7, DONE, "PatchMatch + `healSelection`")
rule(8, MISSING, "جابه‌جایی آگاه از محتوا")
rule(9, DONE, "`BrushPreset.clone` + `BrushRasterizer.addClone` (موج ۹)")
rule(10, HALF, "`Fill.Pattern` در مدل هست؛ قلم مهر الگو نیست")
rule([11, 12], MISSING, "قلم‌موی تاریخچه — به snapshot تاریخچه نیاز دارد که نداریم")
rule(13, DONE, "`BrushPreset.ERASER`")
rule(14, MISSING, "پاک‌کن پس‌زمینه")
rule(15, HALF, "عصای جادویی + «شفاف» در شیت بوم، همان کار در دو گام")
rule(16, MISSING, "بلور به‌صورت قلم‌مو (فیلترش هست)")
rule(17, HALF, "`Retouch.sharpen` روی کل لایه؛ قلم‌مویی نیست")
rule((18, 21), MISSING, "قلم‌موهای انگشتی/روشن/تیره/اسفنج")
rule(22, DONE, "`PenController` + `PathEditor`")
rule(23, MISSING, "قلم آزاد")
rule([24, 25, 26], DONE, "`PathEditor.insert` / `remove` / `retype`")
rule(27, DONE, "")
rule(28, MISSING, "متن عمودی — `TextDirection` فقط افقی دارد")
rule([29, 30], MISSING, "ماسک متنی (با «متن به شکل» + ماسک وکتوری دو-گامی شدنی است)")
rule([31, 32], DONE, "`PathEditor.hitTest`: دسته، بعد نقطه، بعد قطعه")
rule((33, 37), DONE, "`ShapeGeometry` + `ShapeSheet` با پارامتر زنده")
rule(38, HALF, "`SvgPath.read` مسیر دلخواه را می‌خواند؛ کتابخانهٔ شکل سفارشی نیست")
rule(39, DONE, "`panViewport`")
rule(40, DONE, "`transformViewport` چرخش دوربین را می‌گیرد")
rule(41, DONE, "")
rule([42, 43], MISSING, "جفت رنگ پیش‌زمینه/پس‌زمینه اصلاً در مدل نیست")
rule(44, MISSING, "حالت ماسک سریع")
rule(45, DONE, "تنها حالت نمایش")
rule(46, MISSING, "حالت تمام‌صفحه")
rule((47, 53), OUT_OF_SCOPE, "فیلترهای عصبی — مدل ابری")
rule(54, MISSING, "RAW اصلاً رمزگشایی نمی‌شود (به LibRaw روی NDK نیاز دارد)")
rule(55, DONE, "`Liquify` با MLS صُلب")
rule((56, 59), MISSING, "")
rule(60, MISSING, "رنگ روغن")
rule((61, 64), MISSING, "محو میدانی/عنبیه‌ای/تیلت‌شیفت/مسیری")
rule(65, DONE, "`RadialBlur.Kind.SPIN`")
rule(66, MISSING, "محو لنزی (به نقشهٔ عمق نیاز دارد)")
rule(67, DONE, "`PixelFilters.gaussian`، روی رنگ پیش‌ضرب‌شده")
rule(68, MISSING, "محو حرکتی خطی — همان نمونه‌بردار شعاعی با مسیر خطی، کار کمی دارد")
rule(69, DONE, "`RadialBlur` (چرخشی و زوم)")
rule(70, MISSING, "")
rule(71, HALF, "`Blur.bilateral` در `core:imaging` هست، رابط ندارد")
rule(72, HALF, "`Effect.Noise` به‌عنوان افکت لایه هست، به‌عنوان فیلتر پیکسلی نه")
rule((73, 76), MISSING, "حذف نویز")
rule(77, HALF, "بالاگذر داخل `FrequencySeparation` هست، مستقل نیست")
rule([78, 79], HALF, "ریخت‌شناسی روی ماسک انتخاب هست (`grown`)، روی تصویر نه")
rule([80, 81], OUT_OF_SCOPE, "ویدیو/تلویزیون")
rule(82, MISSING, "")
rule((83, 106), MISSING, "گالری فیلترهای هنری/بافتی — هیچ‌کدام نیست")
rule([107, 108], MISSING, "جلوه‌های نوری و درخشش لنز")
rule(109, DONE, "`Adjustment.GradientMap`")
rule(110, DONE, "`Adjustment.PhotoFilter`")
rule(111, MISSING, "میکسر کانال")
rule(112, DONE, "`Adjustment.ColorLookup`")
rule(113, DONE, "`Adjustment.BrightnessContrast`")
rule(114, DONE, "`Adjustment.Levels` با کانال جدا")
rule(115, DONE, "`Adjustment.Curves` + ویرایشگر منحنی")
rule(116, DONE, "`Adjustment.Exposure`")
rule(117, DONE, "`Adjustment.Vibrance`")
rule(118, DONE, "`Adjustment.HueSaturation`")
rule(119, DONE, "`Adjustment.ColorBalance`")
rule(120, DONE, "`Adjustment.BlackWhite`")
rule(121, MISSING, "رنگ انتخابی")
rule(122, DONE, "`Adjustment.Posterize`")
rule(123, DONE, "`Adjustment.Threshold`")
rule(124, DONE, "`Adjustment.Invert`")
rule(125, MISSING, "یکسان‌سازی هیستوگرام")
rule((126, 128), MISSING, "تن/کنتراست/رنگ خودکار")
rule(129, HALF, "با فام/اشباع روی ۱۰۰− شدنی است؛ دکمهٔ مستقیم ندارد")
rule((130, 134), MISSING, "")
rule(135, DONE, "برش به انتخاب (موج ۹)")
rule(136, MISSING, "برش پرسپکتیو")
rule([137, 138], OUT_OF_SCOPE, "برش وب")
rule([139, 140], MISSING, "قطره‌چکان روی بوم — انتخابگر رنگ هست ولی از تصویر نمونه نمی‌گیرد")
rule((141, 143), MISSING, "خط‌کش، یادداشت، شمارشگر")
rule(144, MISSING, "چند تخته‌کار در یک سند")
rule(145, HALF, "ماسک وکتوری همان کار را می‌کند؛ ابزار قاب جدا نیست")
rule(146, DONE, "`SubjectSelection` — بدون مدل (موج ۹)")
rule(147, MISSING, "انتخاب سریع (رشد ناحیه از ضربات قلم)")
rule(148, DONE, "`MagicWand`")
rule([149, 150], DONE, "")
rule(151, DONE, "`setLayerOpacity`")
rule(152, DONE, "`setFillOpacity` — جدا از شفافیت لایه (موج ۹)")
rule((153, 179), DONE, "هر ۲۷ حالت، هم در Kotlin و هم در GLSL؛ تست اگر شاخه‌ای جا بماند می‌شکند")
rule(180, DONE, "`addPaintLayer`")
rule(181, DONE, "`duplicateLayer`")
rule(182, DONE, "`deleteLayer`")
rule(183, DONE, "`groupLayers`")
rule(184, DONE, "`ungroup`")
rule([185, 186, 187], MISSING, "ادغام و تخت‌کردن — هیچ‌کدام نیست")
rule(188, MISSING, "برش حاشیهٔ خالی بوم")
rule(189, DONE, "`resizeCanvas` با لنگر نه‌گانه (موج ۹)")
rule(190, MISSING, "اندازهٔ تصویر (بازنمونه‌برداری خود اثر، جدا از بوم)")
rule((191, 193), MISSING, "چرخش بوم ۹۰/۱۸۰ درجه")
rule(194, MISSING, "صاف‌کردن تصویر")
rule(195, MISSING, "تغییر شکل پرسپکتیو")
rule(196, HALF, "MLS هست (لیکوییفای)؛ نسخهٔ سنجاق‌دار عروسکی نیست")
rule([197, 198], DONE, "دستگیره‌های `Handles`")
rule(199, HALF, "`Transform.skew` در مدل هست؛ دستگیره‌ای آن را نمی‌راند")
rule([200, 201, 202], MISSING, "اعوجاج/پرسپکتیو/پیچش آزاد")
rule(203, DONE, "")
rule(204, MISSING, "تغییر مقیاس آگاه از محتوا (seam carving)")
rule(205, HALF, "`BrushTip.Sampled` در مدل هست؛ انتخابگر فایل ندارد")
rule(206, HALF, "`Fill.Pattern` در مدل هست؛ ساخت الگو از تصویر نیست")
rule(207, MISSING, "")
rule((208, 216), MISSING, "مدیر پیش‌فرض، اکشن، پردازش دسته‌ای")
rule(217, MISSING, "پنل تاریخچه (undo/redo هست، فهرست مراحل نیست)")
rule(218, DONE, "سقف ۵۰ مرحله در `History`")
rule([219, 220], MISSING, "snapshot و پاک‌کردن تاریخچه")
rule((221, 227), DONE, "`BrushPreset`: اندازه، سختی، فاصله، زاویه، گردی، دینامیک شکل، پراکندگی")
rule([228, 229], MISSING, "بافت و قلم‌موی دوگانه")
rule([230, 231], DONE, "`colorJitter`/`hueJitter`… و `flowDynamic`/`opacityDynamic`")
rule(232, DONE, "`StrokeStabilizer`")
rule(233, MISSING, "لبه‌های خیس")
rule(234, HALF, "چند سواچ ثابت در شیت قلم‌مو؛ پنل قابل ویرایش نیست")
rule(235, DONE, "`ColorPickerBody` با ورودی هگز")
rule(236, HALF, "`Fill.Gradient` کامل است؛ ویرایشگر گرادیان روی صفحه نیست")
rule(237, MISSING, "پنل الگو")
rule(238, DONE, "`Library.styles` + `LibrarySheet`")
rule(239, OUT_OF_SCOPE, "کتابخانهٔ ابری")
rule(240, DONE, "`LayerParametersSheet` (موج ۹)")
rule((241, 243), MISSING, "اطلاعات، هیستوگرام، ناوبر")
rule([244, 245], HALF, "`TextSpec`/`ParagraphStyle` همه‌چیز را دارند؛ رابط فقط فونت و رشته را می‌دهد")
rule([246, 247, 248], MISSING, "پنل مسیرها، کانال‌ها، ترکیب‌بندی لایه")
rule(249, DONE, "`Layer.Instance`")
rule(250, DONE, "`exportImage` با انتخاب فرمت و مقیاس")

# ─────────────────────────────────────────────────── section 2: Canva, 251–350
rule((251, 350), MISSING, "")
rule((251, 260), OUT_OF_SCOPE, "ابزارهای مولد/ویدیویی Canva — مدل ابری یا ویدیو")
rule(261, DONE, "`Cutout` — آفلاین و بدون مدل")
rule(262, OUT_OF_SCOPE, "ویدیو")
rule([263, 264], MISSING, "کیت برند: لوگو و پالت ذخیره‌شده")
rule(265, DONE, "مدیر فونت: افزودن فونت شخصی، گروه‌بندی و جست‌وجو")
rule(266, MISSING, "ساخت انبوه از CSV")
rule((267, 272), OUT_OF_SCOPE, "زمان‌بندی، همکاری همزمان، کامنت، تاریخچهٔ نسخه، پوشهٔ ابری")
rule(273, DONE, "قالب پست/استوری/بنر")
rule(274, MISSING, "قالب ارائه")
rule(275, DONE, "قالب پوستر A4")
rule([276, 277, 278], MISSING, "رزومه، لوگو، اینفوگرافیک")
rule(279, OUT_OF_SCOPE, "ویدیو")
rule(280, DONE, "قالب استوری ۱۰۸۰×۱۹۲۰")
rule(281, DONE, "قالب کاور یوتیوب")
rule([282, 283, 284], MISSING, "دعوت‌نامه، گواهی، منو")
rule(285, DONE, "قالب کارت ویزیت")
rule(286, MISSING, "وایت‌برد")
rule(287, OUT_OF_SCOPE, "ساخت وب‌سایت")
rule(288, DONE, "`ShapeSheet`")
rule((289, 291), MISSING, "کتابخانهٔ آیکون/استیکر/تصویرسازی")
rule((292, 294), OUT_OF_SCOPE, "بانک عکس/ویدیو/صدای ابری")
rule(295, HALF, "ماسک وکتوری همان قاب برش است؛ گالری قاب آماده نیست")
rule((296, 300), MISSING, "گرید، نمودار، نقشه، جدول، QR")
rule(301, DONE, "`Effect.DropShadow`")
rule(302, DONE, "سایهٔ نزدیک با فاصلهٔ کم")
rule(303, DONE, "`fillOpacity = 0` + `Effect.Stroke` — پریست «توخالی»")
rule(304, DONE, "`Effect.Extrude` + `Stroke`")
rule(305, DONE, "پریست «نئون» با دو `OuterGlow`")
rule(306, DONE, "`Effect.ChromaticOffset`")
rule(307, DONE, "`TextPath.Arc`")
rule(308, DONE, "`TextWarper` با ۱۵ سبک")
rule([309, 310], DONE, "`WarpStyle.BULGE` و `WAVE`")
rule(311, DONE, "اسکن TTF/OTF/TTC از حافظهٔ دستگاه")
rule(312, MISSING, "پیشنهاد جفت فونت")
rule(313, MISSING, "قطره‌چکان از تصویر")
rule(314, DONE, "")
rule([315, 316], HALF, "مقیاس منفی در `Transform` مجاز است؛ دکمهٔ قرینه‌سازی نیست")
rule(317, MISSING, "ترازبندی و توزیع — **هیچ‌کدام نیست**")
rule([318, 319, 320, 321], DONE, "")
rule(322, MISSING, "کپی/پیست لایه بین اسناد")
rule(323, DONE, "با ژست دو و سه انگشتی هم")
rule(324, MISSING, "نمای شبکه‌ای صفحات")
rule((325, 328), OUT_OF_SCOPE, "ارائه، ضبط، زیرنویس، ترجمه")
rule(329, MISSING, "بررسی دسترسی‌پذیری")
rule([330, 331], DONE, "")
rule(332, HALF, "PDF در جدول فرمت‌ها هست ولی مسیر خروجی‌اش وصل نیست")
rule(333, MISSING, "PDF چاپی و CMYK")
rule(334, OUT_OF_SCOPE, "ویدیو")
rule(335, HALF, "GIF ثابت خوانده/نوشته می‌شود؛ متحرک نه")
rule([336, 337], OUT_OF_SCOPE, "لینک اشتراک و جاسازی")
rule(338, MISSING, "QR")
rule(339, MISSING, "موکاپ")
rule(340, DONE, "قلم‌موی نقاشی روی بوم")
rule(341, MISSING, "پیکسلی‌کردن")
rule(342, DONE, "`PixelFilters.gaussian` محدود به انتخاب")
rule(343, DONE, "برش به انتخاب")
rule(344, MISSING, "بهبود خودکار")
rule(345, DONE, "`Adjustment.GradientMap` دقیقاً همین است")
rule(346, HALF, "با انتخاب سوژه + معکوس + بلور، سه‌گامی شدنی است؛ یک‌دکمه‌ای نیست")
rule(347, MISSING, "تنظیم رنگ پوست")
rule([348, 349], MISSING, "قالب‌های آموزشی/غیرانتفاعی")
rule(350, DONE, "کل رابط راست‌چین، شکل‌دهی و اتصال حروف فارسی با اسکیا")

# ────────────────────────────────────────────────── section 3: PixelLab, 351–450
rule((351, 450), MISSING, "")
rule((351, 362), DONE, "متن، فونت سفارشی، RTL، اندازه، رنگ، حاشیه و سایه با همهٔ پارامترها")
rule(363, HALF, "`Geometry3D` در مدل هست ولی رندرکنندهٔ PBR ساخته نشده؛ «سه‌بعدی» فعلاً `Extrude` است")
rule([364, 365], DONE, "`Effect.Extrude` با `steps`/`stepOffset` و رنگ نزدیک و دور")
rule((366, 368), MISSING, "چرخش سه‌بعدی روی سه محور — به رندرکنندهٔ PBR نیاز دارد")
rule([369, 370, 371], DONE, "`ParagraphStyle`")
rule(372, DONE, "`TextWarper` — ۱۵ سبک، روی خط‌دور شکل‌گرفته نه روی خط پایه")
rule(373, MISSING, "پرسپکتیو متن")
rule((374, 378), DONE, "`ShapeSheet` با پارامتر زنده")
rule(379, DONE, "انتخابگر تصویر (موج ۹)")
rule(380, MISSING, "گرفتن مستقیم از دوربین")
rule(381, HALF, "عصای جادویی + جداسازی سوژه هست؛ کروماکی اختصاصی نیست")
rule(382, DONE, "")
rule(383, HALF, "`Layer.Image.crop` در مدل هست؛ رابط برش تصویر نیست (برش بوم هست)")
rule(384, DONE, "دستگیرهٔ چرخش با چفت‌شدن")
rule(385, HALF, "مقیاس منفی مجاز است؛ دکمه ندارد")
rule(386, MISSING, "استیکر داخلی")
rule((387, 392), DONE, "پنل لایهٔ تودرتو با ترتیب، قفل، اختفا، تکثیر و حذف")
rule(393, MISSING, "ادغام لایه‌ها")
rule(394, DONE, "`.pxl` — zip با سند و دارایی‌ها، نوشتن اتمیک")
rule(395, HALF, "خروجی JPEG هست؛ لغزندهٔ کیفیت ندارد")
rule(396, DONE, "")
rule(397, DONE, "`PsdWriter` — لایه‌دار، با نام و حالت ترکیب و بریدگی")
rule(398, DONE, "با لنگر نه‌گانه")
rule(399, DONE, "`setCanvasBackground`")
rule([400, 401], HALF, "`CanvasSpec.background` هر `Fill`ی را می‌پذیرد؛ رابط فقط رنگ ساده می‌دهد")
rule(402, MISSING, "قطره‌چکان")
rule(403, DONE, "سواچ‌های ثابت در شیت قلم‌مو و بوم")
rule(404, MISSING, "ذخیرهٔ رنگ سفارشی در پالت")
rule((405, 411), DONE, "قلم آزاد با اندازه/رنگ/شفافیت، پاک‌کن، و undo چندمرحله‌ای")
rule([412, 413], MISSING, "ترازبندی و توزیع")
rule([414, 415], DONE, "")
rule(416, DONE, "`dragTo(lockAspect = true)`")
rule(417, DONE, "`SnapEngine` با خطوط راهنمای زنده")
rule(418, MISSING, "شبکهٔ روی بوم")
rule(419, MISSING, "حالت تمام‌صفحه")
rule(420, DONE, "`Gestures` — زوم، چرخش و پن با چند انگشت")
rule(421, DONE, "`Adjustment.BlackWhite`")
rule(422, HALF, "با `PhotoFilter` شدنی است؛ پریست «سپیا» آماده نیست")
rule(423, DONE, "`Adjustment.Invert`")
rule([424, 425], DONE, "`Adjustment.BrightnessContrast`")
rule([426, 427, 428], HALF, "ماسک وکتوری با بیضی و ستاره هست؛ قلب و گالری شکل برش نیست")
rule([429, 430], DONE, "هر لایهٔ متن یا تصویری با شفافیت، همان واترمارک است")
rule((431, 433), MISSING, "ورودی عددی مختصات، اندازه و زاویه — همه‌چیز با دستگیره است")
rule(434, HALF, "فقط فارسی؛ زیرساخت رشته‌ها چندزبانه نیست")
rule(435, HALF, "فقط تم تاریک، و این تصمیم است نه کمبود: رابط روشن دور اثر، قضاوت رنگ را عوض می‌کند")
rule([436, 437], DONE, "بدون تبلیغ و کاملاً آفلاین")
rule(438, DONE, "بدون هیچ کتابخانهٔ سنگین شخص ثالث")
rule(439, DONE, "`minSdk 26`")
rule(440, DONE, "خروجی تا ×۴ با بودجهٔ حافظه")
rule(441, DONE, "`TextPath.Arc` و `TextPath.Custom`")
rule(442, DONE, "پریست «نئون»")
rule(443, HALF, "پریست «طلایی» با گرادیان و پخ؛ متریال فلزی واقعی به PBR نیاز دارد")
rule(444, MISSING, "متریال چوبی")
rule(445, DONE, "`Fill.Backdrop` — پریست «شیشه‌ای»")
rule(446, DONE, "`applyStyle` استایل کامل را روی لایهٔ دیگر می‌گذارد")
rule(447, DONE, "پیش‌نمایش هر فونت با متن خودش")
rule(448, OUT_OF_SCOPE, "دانلود فونت از اینترنت")
rule(449, DONE, "`SubjectSelection` + `Cutout.refine`")
rule(450, MISSING, "کشیدن و رهاکردن فایل")

# ─────────────────────────────────────────────────── section 4: Picsart, 451–550
rule((451, 550), MISSING, "")
rule([451, 452, 453], OUT_OF_SCOPE, "مولد با مدل ابری")
rule(454, DONE, "`Cutout` + `SubjectSelection`، آفلاین")
rule([455, 456], MISSING, "بزرگ‌نمایی و بهبود کیفیت با مدل")
rule(457, DONE, "`Retouch.smoothSkin` با جداسازی فرکانسی")
rule(458, DONE, "`Retouch.heal` روی انتخاب")
rule(459, DONE, "`Liquify` با MLS صُلب")
rule((460, 465), MISSING, "آرایش دیجیتال، سفیدی دندان، قرمزی چشم، رنگ مو و چشم")
rule((466, 473), MISSING, "کتابخانهٔ فیلترهای آماده — هیچ پریست فیلتری نداریم")
rule([474, 475, 476], DONE, "`BrightnessContrast` و `HueSaturation`")
rule([477, 478], DONE, "`ColorBalance` و `PhotoFilter`")
rule([479, 480], DONE, "`Adjustment.Levels` با ورودی/خروجی جدا")
rule(481, MISSING, "وینیت")
rule(482, MISSING, "تیلت‌شیفت")
rule(483, DONE, "`Retouch.sharpen`")
rule(484, MISSING, "وضوح (clarity)")
rule(485, DONE, "برش به انتخاب + نسبت‌های آماده در شیت بوم")
rule(486, DONE, "")
rule(487, HALF, "مقیاس منفی مجاز است؛ دکمه ندارد")
rule([488, 489, 490], MISSING, "پرسپکتیو، کشش، اعوجاج")
rule(491, DONE, "مهر کپی (موج ۹)")
rule(492, DONE, "`BrushRasterizer` با شش پریست")
rule([493, 494], HALF, "ماژیک هست؛ نئون به‌عنوان قلم‌مو نه (به‌عنوان افکت لایه هست)")
rule([495, 496], MISSING, "قلم‌موی برف و درخشش — به نوک تصویری نیاز دارند")
rule(497, DONE, "")
rule(498, DONE, "نقاشی روی لایهٔ مستقل")
rule(499, DONE, "")
rule(500, DONE, "قراردادن تصویر به‌عنوان لایه (موج ۹)")
rule(501, DONE, "دستی با کمند، خودکار با انتخاب سوژه")
rule(502, DONE, "`SubjectSelection`")
rule([503, 504, 505], MISSING, "استیکر و ساخت استیکر")
rule(506, DONE, "")
rule(507, DONE, "هر فونتی که روی دستگاه باشد")
rule(508, DONE, "")
rule(509, DONE, "سایه، حاشیه و منحنی — همه هستند")
rule(510, DONE, "`ShapeSheet`")
rule(511, HALF, "ماسک وکتوری؛ گالری قاب نیست")
rule(512, DONE, "ماسک رستری و وکتوری و برش")
rule([513, 514], DONE, "۲۷ حالت ترکیب روی هر لایه")
rule([515, 516], MISSING, "کلاژ با چیدمان آماده")
rule((517, 528), OUT_OF_SCOPE, "ویرایش ویدیو — به‌خواست شما بیرون از دامنه است")
rule(529, MISSING, "ساخت میم")
rule(530, DONE, "`CurveEditor` با کانال جدا")
rule(531, MISSING, "تنظیم رنگ پوست")
rule([532, 533], MISSING, "پراکندگی ذرات و دو نوردهی")
rule((534, 536), MISSING, "افکت‌های جادویی، درخشش لنز، بوکه")
rule(537, DONE, "`PixelFilters` محدود به انتخاب")
rule([538, 539], MISSING, "پیکسلی‌کردن و نویز به‌عنوان فیلتر")
rule(540, MISSING, "وینیت")
rule([541, 542], DONE, "")
rule(543, HALF, "ذخیره در گالری با MediaStore هست؛ اشتراک مستقیم در اپ‌ها نه")
rule((544, 546), OUT_OF_SCOPE, "شبکهٔ اجتماعی داخل اپ")
rule(547, DONE, "پروژه‌های ذخیره‌شده همان پیش‌نویس‌اند")
rule(548, DONE, "undo/redo با تاریخچهٔ درهم‌بافتهٔ سند و پیکسل")
rule(549, HALF, "فشار قلم در مدل دینامیک هست؛ اکثر گوشی‌ها فشار گزارش نمی‌کنند")
rule(550, DONE, "تنها حالت")

# ──────────────────────────────────────────────────── section 5: HiPaint, 551–650
rule((551, 650), MISSING, "")
rule(551, DONE, "`StampPlanner` + `BrushRasterizer`")
rule(552, HALF, "شش پریست، نه صدها")
rule((553, 560), MISSING, "قلم‌موهای مدادی/آبرنگ/روغن/پاستل/زغال/جوهر — به نوک تصویری و بافت نیاز دارند")
rule(561, HALF, "`BrushPreset` کاملاً قابل ساخت است؛ رابط ساخت و ذخیرهٔ پریست نیست")
rule((562, 565), DONE, "اندازه، شفافیت، جریان و فاصله — همه در شیت قلم‌مو")
rule(566, DONE, "`ControlSource.PRESSURE`")
rule(567, DONE, "`ControlSource.TILT`")
rule(568, DONE, "`StrokeStabilizer` — ریسمان کشیده، نه میانگین")
rule(569, DONE, "بدون سقف")
rule(570, DONE, "`renameLayer`")
rule(571, DONE, "")
rule(572, DONE, "۲۷ حالت")
rule(573, DONE, "`LayerMask` با چگالی، وارونگی و پَر")
rule(574, DONE, "`clipped`")
rule(575, DONE, "قفل شفافیت در پرکردن (موج ۹)")
rule(576, DONE, "`setLayerLocked`")
rule((577, 579), MISSING, "ادغام و تخت‌کردن")
rule((580, 585), DONE, "مستطیل، بیضی، کمند، چندضلعی و عصای جادویی")
rule(586, HALF, "پرکردن انتخاب هست؛ سطل رنگ با تلورانس روی نقطه نه")
rule(587, MISSING, "قطره‌چکان")
rule(588, DONE, "پاک‌کن با همان تنظیمات قلم‌مو")
rule([589, 590], MISSING, "انگشتی و روشن/تیره")
rule(591, HALF, "مقیاس و چرخش هست؛ کج‌کردن و اعوجاج نه")
rule((592, 594), DONE, "")
rule((595, 599), MISSING, "خط‌کش، تقارن و راهنمای پرسپکتیو")
rule(600, MISSING, "شبکه")
rule((601, 610), OUT_OF_SCOPE, "انیمیشن فریم‌به‌فریم و خروجی ویدیو")
rule((611, 613), HALF, "رویداد فشار و شیب خوانده می‌شود؛ سازگاری اختصاصی با قلم خاص نه")
rule(614, MISSING, "میانبر قابل سفارشی‌سازی")
rule([615, 616], DONE, "`CanvasGesture.Undo` و `Redo`")
rule(617, DONE, "")
rule(618, HALF, "`CanvasSpec.dpi` هست و در خروجی می‌رود؛ رابط انتخاب DPI نیست")
rule(619, DONE, "فضای کاری RGB")
rule(620, MISSING, "فضای خاکستری")
rule(621, DONE, "`.pxl`")
rule([622, 623, 624], DONE, "PNG، JPEG و PSD لایه‌دار")
rule(625, HALF, "PDF در جدول فرمت‌ها هست، مسیر خروجی وصل نیست")
rule([626, 627], DONE, "`ColorPickerBody` — مربع اشباع/روشنی + نوار فام + هگز")
rule(628, MISSING, "ذخیرهٔ رنگ مورد علاقه")
rule(629, HALF, "`Fill.Gradient` خطی و شعاعی و مخروطی کامل است؛ ویرایشگر گرادیان روی صفحه نیست")
rule(630, HALF, "`Fill.Pattern` در مدل هست، رابط ندارد")
rule([631, 632], MISSING, "تصویر مرجع و پنجرهٔ شناور")
rule(633, MISSING, "حالت تمرکز")
rule(634, HALF, "فقط تاریک — تصمیم است")
rule(635, MISSING, "جابه‌جایی پنل‌ها")
rule(636, HALF, "فقط فارسی")
rule((637, 640), MISSING, "جامعهٔ قلم‌مو، واردات و صادرات پریست")
rule(641, DONE, "")
rule(642, DONE, "")
rule(643, MISSING, "نقاشی متقارن")
rule(644, MISSING, "تبدیل خط دست‌نویس به شکل")
rule(645, DONE, "`setCanvasBackground`")
rule(646, DONE, "بوم بدون پس‌زمینه شفاف رندر می‌شود")
rule(647, MISSING, "نوار لغزندهٔ تاریخچه")
rule([648, 649], MISSING, "ذخیرهٔ خودکار و پشتیبان — ذخیره دستی و اتمیک است")
rule(650, DONE, "هیچ تبلیغی نیست")

# ─────────────────────────────────────────────────── section 6: PhotoRoom, 651–750
rule((651, 750), MISSING, "")
rule(651, DONE, "`SubjectSelection` + `Cutout.refine` — بدون مدل و بدون شبکه")
rule(652, DONE, "فیلتر راهنما با راهنمای رنگی: تار مو با کرومینانس جدا می‌شود نه با روشنایی")
rule(653, HALF, "روی گوشی هدف قابل قبول است ولی سنجش زمان‌بندی نشده")
rule(654, DONE, "`Retouch.heal` با PatchMatch")
rule((655, 658), MISSING, "سایهٔ مصنوعی زیر سوژه با زاویه و محو — `DropShadow` هست ولی سایهٔ زمینی نه")
rule(659, HALF, "`Effect.Reflection` هست؛ پریست انعکاس محصول نیست")
rule((660, 663), OUT_OF_SCOPE, "پس‌زمینهٔ مولد با مدل")
rule((664, 666), MISSING, "قالب فروشگاهی")
rule((667, 670), MISSING, "ویرایش دسته‌جمعی")
rule(671, DONE, "`resizeCanvas`")
rule(672, DONE, "نسبت‌های آماده در شیت بوم")
rule([673, 674], DONE, "")
rule(675, DONE, "لوگو به‌عنوان لایهٔ تصویری با شفافیت")
rule(676, MISSING, "کیت برند")
rule([677, 678], MISSING, "استیکر و قاب آماده")
rule([679, 680], HALF, "تنظیم‌ها کامل‌اند؛ فیلترهای آمادهٔ رنگی نیست")
rule(681, DONE, "`PixelFilters.gaussian` روی انتخاب معکوس‌شدهٔ سوژه")
rule(682, DONE, "")
rule(683, HALF, "مدل گرادیان کامل است؛ رابطش نیست")
rule(684, DONE, "قراردادن تصویر به‌عنوان لایه")
rule([685, 686], DONE, "")
rule(687, DONE, "هیچ واترمارکی گذاشته نمی‌شود")
rule((688, 694), OUT_OF_SCOPE, "API، افزونهٔ فروشگاه، نسخهٔ وب، ابر")
rule(695, HALF, "عصای جادویی + شفاف‌کردن")
rule(696, MISSING, "بزرگ‌نمایی با مدل")
rule(697, HALF, "با انتخاب سوژه + بلور پس‌زمینه، چندگامی")
rule(698, MISSING, "قالب فصلی")
rule(699, DONE, "`applyStyle`")
rule(700, DONE, "JPG، PNG، HEIC و WebP همه خوانده می‌شوند")
rule(701, DONE, "JPG، PNG و WebP نوشته می‌شوند")
rule([702, 703], DONE, "")
rule(704, HALF, "مقیاس منفی مجاز؛ دکمه ندارد")
rule([705, 706], HALF, "`Effect.Stroke` روی لایه هست؛ حاشیهٔ دور خود بوم نیست")
rule(707, DONE, "ماسک وکتوری با مستطیل گردگوشه")
rule([708, 709], DONE, "لایهٔ متن یا تصویر با شفافیت")
rule(710, MISSING, "نمای قبل و بعد")
rule((711, 719), OUT_OF_SCOPE, "آموزش درون‌برنامه، ابر، تیم، اشتراک")
rule([720, 721], DONE, "همان پالایش لبه که برای مو ساخته شده، برای شیشه و خز هم همان است")
rule(722, MISSING, "تصحیح رنگ خودکار")
rule([723, 724], OUT_OF_SCOPE, "کاتالوگ و ویدیو")
rule([725, 726], MISSING, "نشان تخفیف")
rule((727, 729), MISSING, "کلاژ و چیدمان خودکار")
rule((730, 732), OUT_OF_SCOPE, "SLA و ابر — هیچ تصویری از دستگاه خارج نمی‌شود، پس موضوعیت ندارد")
rule(733, MISSING, "عملیات سریع")
rule(734, DONE, "undo/redo")
rule(735, HALF, "پروژه ذخیره و دوباره باز می‌شود؛ دکمهٔ تکثیر پروژه نیست")
rule([736, 737], DONE, "زوم و پن با ژست")
rule(738, OUT_OF_SCOPE, "میانبر صفحه‌کلید وب")
rule(739, HALF, "فقط تاریک")
rule((740, 744), OUT_OF_SCOPE, "ابر، ورود، صورتحساب، پشتیبانی")
rule(745, MISSING, "گالری الهام")
rule(746, MISSING, "بهبود خودکار")
rule([747, 748], DONE, "`PhotoFilter` و `ColorBalance`")
rule(749, MISSING, "وینیت")
rule(750, HALF, "خروجی WebP هست؛ بهینه‌سازی حجم تنظیم‌شدنی نیست")

# ─────────────────────────────────────────────────── section 7: AirBrush, 751–850
rule((751, 850), MISSING, "")
rule([751, 752], DONE, "`Retouch.smoothSkin` — جداسازی فرکانسی، نه بلور")
rule(753, DONE, "`Retouch.heal`")
rule(754, HALF, "همان ابزار ترمیم؛ حالت اختصاصی آکنه نیست")
rule([755, 756], HALF, "با ترمیم شدنی است؛ ابزار مخصوص چروک و پف نیست")
rule([757, 758], MISSING, "سفید کردن دندان")
rule([759, 760], MISSING, "روشن و بزرگ کردن چشم")
rule(761, DONE, "`Liquify` — هل دادن، باد کردن، جمع کردن و پیچاندن")
rule((762, 768), HALF, "همه با `Liquify` دستی شدنی‌اند؛ ابزار تشخیص چهره و پریست ناحیه‌ای نیست")
rule([769, 770], MISSING, "برنزه کردن")
rule(771, MISSING, "یکدست‌کردن رنگ پوست")
rule(772, MISSING, "کک و مک")
rule((773, 782), MISSING, "آرایش دیجیتال — به تشخیص نقاط چهره نیاز دارد که نداریم")
rule((783, 786), MISSING, "کتابخانهٔ فیلتر آماده")
rule((787, 790), DONE, "روشنایی، کنتراست، اشباع و دما — همه به‌صورت لایهٔ تنظیم برگشت‌پذیر")
rule(791, MISSING, "وینیت")
rule(792, DONE, "`Retouch.sharpen`")
rule([793, 794], DONE, "")
rule(795, HALF, "مقیاس منفی مجاز؛ دکمه ندارد")
rule(796, DONE, "")
rule([797, 798], MISSING, "استیکر و قاب")
rule(799, MISSING, "قرمزی چشم")
rule(800, HALF, "با انتخاب + سیاه‌وسفید روی بقیه شدنی است؛ یک‌دکمه‌ای نیست")
rule([801, 802], HALF, "بلور محدود به انتخاب هست؛ تیلت‌شیفت با شیب تدریجی نه")
rule(803, DONE, "مهر کپی")
rule(804, MISSING, "نمای قبل و بعد")
rule([805, 806], MISSING, "ذخیرهٔ Look و اعمال دسته‌جمعی")
rule(807, DONE, "لغزنده‌ها با کشیدن دقیق، ورود عددی و بازگشت به پیش‌فرض")
rule([808, 809], MISSING, "آموزش و گالری")
rule([810, 811], DONE, "تا ×۴ و بدون افت")
rule(812, HALF, "ذخیره در گالری هست؛ اشتراک مستقیم نه")
rule([813, 814], DONE, "هیچ چیزی پشت پرداخت نیست")
rule(815, OUT_OF_SCOPE, "")
rule(816, HALF, "فقط فارسی")
rule(817, DONE, "تنها حالت")
rule([818, 819], MISSING, "رنگ مو و چشم")
rule([820, 821], HALF, "با ترمیم و تیزی نزدیک می‌شود؛ ابزار مخصوص نیست")
rule(822, DONE, "قلم‌مو روی لایهٔ جدا")
rule(823, MISSING, "پرو مجازی")
rule(824, DONE, "حذف سوژه + گذاشتن تصویر پشتش")
rule(825, DONE, "همان جداسازی؛ به خز و مو حساس است")
rule(826, DONE, "اندازه، سختی، جریان و شفافیت")
rule(827, DONE, "")
rule(828, DONE, "استخر بافت، بودجهٔ حافظه پیش از رندر")
rule(829, HALF, "فقط اندروید ۸ به بالا")
rule(830, DONE, "هیچ تصویری هرگز از دستگاه خارج نمی‌شود")
rule((831, 836), HALF, "با `Liquify` دستی شدنی‌اند؛ پریست ناحیه‌ای نیست")
rule(837, MISSING, "")
rule((838, 842), DONE, "قلم‌موی دستی برای هر کدام، با اندازه و سختی")
rule([843, 844], MISSING, "زیباسازی خودکار")
rule(845, HALF, "با انتخاب رنگی + سیاه‌وسفید شدنی؛ یک‌دکمه‌ای نیست")
rule(846, MISSING, "دو نوردهی — با حالت ترکیب Screen شدنی است")
rule(847, MISSING, "نشت نور")
rule(848, MISSING, "حذف گرد و غبار خودکار")
rule(849, MISSING, "مهر تاریخ")
rule(850, MISSING, "کلاژ")

# ──────────────────────────────────────────────────── section 8: Tenada, 851–950
rule((851, 950), MISSING, "")
rule(851, HALF, "`Geometry3D` در مدل هست، رندرکنندهٔ PBR ساخته نشده — «سه‌بعدی» فعلاً برجستگیِ `Extrude` است")
rule(852, MISSING, "چرخش ۳۶۰ درجه در فضای سه‌بعدی")
rule(853, DONE, "`Effect.Extrude.steps` × `stepOffset`")
rule((854, 860), MISSING, "متریال‌های فلز، شیشه، نئون، چوب، پلاستیک، آتش و یخ — به PBR نیاز دارند")
rule([861, 862], DONE, "رنگ اصلی و رنگ عمق (`nearFill`/`farFill`)")
rule([863, 864], MISSING, "لوگوی سه‌بعدی")
rule((865, 870), MISSING, "جلوه‌های ویژه: دود، جرقه، ذرات، پرتو نور، انعکاس")
rule((871, 876), OUT_OF_SCOPE, "انیمیشن — این اپ ویدیو نمی‌سازد")
rule((877, 880), MISSING, "کنترل دوربین سه‌بعدی")
rule((881, 886), MISSING, "نورپردازی صحنه — `GlobalLight` برای افکت‌ها هست ولی نور صحنهٔ سه‌بعدی نیست")
rule(887, DONE, "`CanvasSpec.background`")
rule(888, DONE, "")
rule(889, HALF, "مدل گرادیان هست، رابطش نیست")
rule(890, DONE, "تصویر به‌عنوان لایهٔ پشت")
rule(891, DONE, "خروجی PNG با پس‌زمینهٔ شفاف")
rule((892, 895), MISSING, "قالب آمادهٔ سه‌بعدی و اینترو")
rule(896, DONE, "هر فونت ضخیمی که روی دستگاه باشد")
rule(897, DONE, "")
rule(898, DONE, "فارسی و عربی کاملاً پشتیبانی می‌شوند — نه «با تنظیمات خاص»")
rule((899, 901), DONE, "`ParagraphStyle`")
rule(902, HALF, "`TextPath.Arc` در صفحه هست؛ منحنی در فضای سه‌بعدی نه")
rule([903, 904], DONE, "`Effect.Bevel` با عمق، اندازه و نرمی")
rule([905, 906], DONE, "`Effect.Stroke` با ضخامت، رنگ و موقعیت")
rule((907, 909), OUT_OF_SCOPE, "خروجی ویدیو")
rule(910, DONE, "")
rule(911, OUT_OF_SCOPE, "GIF متحرک")
rule((912, 919), DONE, "پنل لایه با قفل، اختفا، ترتیب، گروه، تکثیر، حذف و undo")
rule(920, DONE, "`.pxl`")
rule([921, 922], DONE, "رابط تک‌دستی، ژست چندلمسی")
rule(923, DONE, "رندر روی GPU در همان فریم")
rule([924, 925], MISSING, "دو کیفیت رندر جدا — همیشه کیفیت کامل است")
rule(926, MISSING, "شبکه")
rule(927, DONE, "`SnapEngine`")
rule(928, MISSING, "سفارشی‌سازی رابط")
rule(929, DONE, "تنها حالت")
rule([930, 931], MISSING, "آموزش و گالری")
rule(932, HALF, "ذخیره در گالری هست؛ اشتراک مستقیم نه")
rule(933, DONE, "MediaStore")
rule([934, 935], DONE, "هیچ واترمارکی گذاشته نمی‌شود")
rule(936, DONE, "همه‌چیز باز است")
rule(937, OUT_OF_SCOPE, "")
rule(938, HALF, "فقط فارسی")
rule([939, 940], DONE, "استخر بافت و بودجهٔ حافظه پیش از رندر")
rule([941, 942], DONE, "`Effect.DropShadow` مستقل روی متن")
rule([943, 944], DONE, "`Effect.OuterGlow`")
rule([945, 946], DONE, "`Effect.Reflection` با فاصله و محو")
rule([947, 948], MISSING, "سطح زمین برای سایه و انعکاس")
rule([949, 950], MISSING, "نقشهٔ محیطی — به PBR نیاز دارد")

# ───────────────────────────────────── section 9: advanced/technical, 951–1500
rule((951, 1500), MISSING, "")
rule(951, MISSING, "حاشیهٔ سه‌بعدی")
rule(952, MISSING, "بافت‌های مختلف روی سطوح مختلف")
rule((953, 956), OUT_OF_SCOPE, "کی‌فریم، منحنی حرکت، حلقه، صدا — انیمیشن و ویدیو")
rule(957, DONE, "`StylePreset` — استایل ذخیره‌شده و قابل اعمال")
rule(958, HALF, "قالب اندازهٔ سند هست؛ ذخیرهٔ کل صحنه به‌عنوان قالب نه")
rule(959, MISSING, "واردات شیء سه‌بعدی")
rule((960, 964), OUT_OF_SCOPE, "مسیر دوربین، عمق میدان، اعوجاج رنگی متحرک، دانهٔ فیلم")
rule(963, HALF, "`Effect.ChromaticOffset` روی لایه هست؛ نسخهٔ سینمایی روی کل صحنه نه")
rule(965, HALF, "چهارده تنظیم روی لایه هست؛ درجه‌بندی روی کل سند نه")
rule(966, MISSING, "وینیت")
rule(967, DONE, "هر نسبتی با `resizeCanvas`")
rule(968, MISSING, "مناطق امن")
rule(969, DONE, "`FontCatalog.resolve` با تنزل ایمن و هشدار")
rule(970, DONE, "`TextDirection`: خودکار، چپ‌به‌راست، راست‌به‌چپ")
rule([971, 972], DONE, "`letterSpacing` و `wordSpacing`")
rule([973, 974], DONE, "`TextAlign` و جعبهٔ متن")
rule(975, MISSING, "اندازهٔ خودکار متن")
rule(976, DONE, "`wrap()` در `TextRasterizer` — شکستن روی فاصله، نه وسط کلمه")
rule(977, MISSING, "لیست نقطه‌ای")
rule((978, 980), MISSING, "پس‌زمینهٔ رنگی پشت متن با گردی و فاصلهٔ داخلی")
rule(981, DONE, "")
rule(982, DONE, "۲۷ حالت")
rule([983, 984, 985], DONE, "`LayerMask` با `inverted` و `feather`")
rule((986, 989), DONE, "انتخاب، جابه‌جایی، مقیاس و چرخش با دستگیره")
rule(990, MISSING, "بازنشانی تبدیل")
rule((991, 998), MISSING, "ترازبندی و توزیع — **هشت مورد، هیچ‌کدام نیست**")
rule([999, 1000], DONE, "")
rule([1001, 1002], DONE, "HEIC خوانده می‌شود و خروجی هر فرمت دیگری ممکن است")
rule(1003, HALF, "`ColorSettings` در سند هست؛ پروفایل ICC خوانده/نوشته نمی‌شود")
rule(1004, HALF, "`ColorSettings.precision` هست و PSD ۱۶بیتی خوانده می‌شود؛ ترکیب داخلی ۸بیتی است")
rule([1005, 1006], MISSING, "CMYK و LAB")
rule(1007, MISSING, "انتخاب بازهٔ رنگی")
rule(1008, MISSING, "انتخاب ناحیهٔ فوکوس")
rule(1009, OUT_OF_SCOPE, "جایگزینی آسمان با مدل")
rule([1010, 1011], OUT_OF_SCOPE, "فیلتر عصبی")
rule([1012, 1013], HALF, "مدل الگو و نوک تصویری هست؛ ساختشان از تصویر نیست")
rule(1014, OUT_OF_SCOPE, "همگام‌سازی ابری")
rule(1015, MISSING, "خروجی تخته‌کارها به PDF")
rule([1016, 1017, 1018], OUT_OF_SCOPE, "اسکریپت و اتوماسیون دسکتاپ")
rule(1019, DONE, "خروجی بهینه با انتخاب فرمت و مقیاس")
rule(1020, OUT_OF_SCOPE, "برش HTML")
rule((1021, 1028), OUT_OF_SCOPE, "چاپ فیزیکی، ابر، ویدیو و ارائهٔ Canva")
rule(1029, DONE, "`PsdWriter` — لایه‌ها با نام و حالت ترکیب می‌روند (متن به‌صورت پیکسل، نه لایهٔ متنی)")
rule(1030, DONE, "`Fill.Gradient` روی متن")
rule(1031, HALF, "`Fill.Pattern` در مدل هست، رابط ندارد")
rule(1032, HALF, "`SvgPath.read` داده‌های مسیر را می‌خواند؛ خوانندهٔ فایل SVG کامل نیست")
rule(1033, DONE, "`Effect.Stroke` بیرونی")
rule(1034, OUT_OF_SCOPE, "مولد پس‌زمینه")
rule(1035, MISSING, "تزئینات آماده")
rule(1036, MISSING, "پراکندگی")
rule(1037, DONE, "`CurveEditor`")
rule(1038, DONE, "بدون سقف لایه")
rule(1039, MISSING, "اصلاح پرسپکتیو")
rule(1040, MISSING, "رد کردن کف دست")
rule([1041, 1042], MISSING, "منوی سریع و میانبر سفارشی")
rule([1043, 1044], MISSING, "تقارن و راهنمای پرسپکتیو")
rule(1045, MISSING, "خواندن قلم‌موی ABR فتوشاپ")
rule(1046, MISSING, "تراز خودکار در مرکز")
rule(1047, HALF, "قالب اندازه هست؛ ذخیرهٔ قالب کاربر نه")
rule(1048, MISSING, "واترمارک دسته‌جمعی")
rule(1049, DONE, "WebP خوانده و نوشته می‌شود")
rule((1050, 1053), MISSING, "انتقال آرایش و کار روی مو")
rule(1054, MISSING, "پروفایل برجستگی مقعر و محدب")
rule(1055, DONE, "خروجی PNG با کانال آلفا")
rule([1056, 1057], OUT_OF_SCOPE, "انیمیشن")
rule(1058, DONE, "پیش‌نمایش زنده روی GPU")
rule([1059, 1060, 1061], HALF, "`Cutout.refine` همان کار را می‌کند و قلم پالایش هم دارد؛ فضای کاری جدا و انتخاب خروجی نیست")
rule(1062, DONE, "ترمیم با PatchMatch روی انتخاب")
rule(1063, OUT_OF_SCOPE, "")
rule([1064, 1065], OUT_OF_SCOPE, "فیلتر عصبی")
rule((1066, 1069), OUT_OF_SCOPE, "ویدیو، ابر و گردش کار Canva")
rule(1070, MISSING, "چرخش سه‌بعدی")
rule(1071, HALF, "پروژه ذخیره می‌شود؛ ثبتش به‌عنوان قالب نه")
rule(1072, DONE, "لایهٔ تنظیم روی لایهٔ تصویر، و فیلتر پیکسلی")
rule([1073, 1074, 1075], OUT_OF_SCOPE, "مدل ابری و ویدیو")
rule((1076, 1077), OUT_OF_SCOPE, "انیمیشن")
rule(1078, DONE, "قفل شفافیت در پرکردن")
rule(1079, OUT_OF_SCOPE, "سایهٔ تولیدشده با مدل")
rule(1080, OUT_OF_SCOPE, "API")
rule(1081, HALF, "با `Liquify` دستی")
rule(1082, HALF, "با ترمیم PatchMatch")
rule([1083, 1084, 1085], MISSING, "انیمیشن لوگو، واردات وکتور به سه‌بعدی، سیستم ذرات")
rule(1086, DONE, "تم تاریک")
rule(1087, DONE, "")
rule(1088, DONE, "")
rule(1089, DONE, "برش و چرخش")
rule(1090, DONE, "")
rule(1091, DONE, "MediaStore")
rule(1092, HALF, "ذخیره هست، اشتراک مستقیم نه")
rule(1093, DONE, "")
rule(1094, DONE, "بودجهٔ حافظه پیش از رندر، با پیشنهاد جایگزین")
rule(1095, DONE, "منبع باز")
rule(1096, DONE, "چیدمان یک‌سوم پایین، برای دست‌رس شست")
rule(1097, HALF, "فقط فارسی")
rule([1098, 1099], DONE, "")
rule(1100, DONE, "هیچ واترمارکی نیست")
rule(1101, DONE, "شیت قلم‌مو")
rule([1102, 1103], HALF, "مدل کامل است؛ پنل کاراکتر و پاراگراف روی صفحه نیست")
rule(1104, DONE, "پنل لایهٔ تودرتو")
rule([1105, 1106], MISSING, "پنل کانال و مسیر")
rule(1107, MISSING, "پنل تاریخچه")
rule(1108, MISSING, "پنل اکشن")
rule(1109, DONE, "شیت پارامترهای لایه (موج ۹)")
rule(1110, OUT_OF_SCOPE, "کتابخانهٔ ابری")
rule(1111, DONE, "شیت شکل")
rule(1112, DONE, "شیت فونت")
rule(1113, DONE, "قراردادن تصویر از حافظه")
rule(1114, DONE, "فهرست پروژه‌ها")
rule(1115, MISSING, "پنل افزونه")
rule(1116, MISSING, "پنل کیت برند")
rule(1117, MISSING, "پیشنهاد ترکیب رنگ و فونت")
rule(1118, DONE, "شیت فونت")
rule(1119, DONE, "شیت بوم")
rule(1120, DONE, "شیت شکل")
rule(1121, MISSING, "پنل استیکر")
rule(1122, DONE, "پنل لایه")
rule(1123, DONE, "نوار ابزار")
rule(1124, DONE, "شیت افکت و شیت فیلتر")
rule(1125, DONE, "شیت ترمیم")
rule(1126, MISSING, "پنل استیکر")
rule(1127, DONE, "شیت متن")
rule(1128, DONE, "شیت قلم‌مو")
rule(1129, DONE, "پنل لایه")
rule(1130, DONE, "انتخابگر رنگ")
rule(1131, MISSING, "پنل تنظیمات برنامه")
rule(1132, DONE, "شیت کتابخانه")
rule(1133, DONE, "پس‌زمینهٔ بوم در شیت بوم")
rule(1134, MISSING, "پنل سایهٔ زمینی")
rule(1135, DONE, "شیت متن")
rule(1136, DONE, "شیت ترمیم")
rule(1137, MISSING, "پنل آرایش")
rule(1138, DONE, "شیت فیلتر")
rule(1139, DONE, "نوار ابزار")
rule(1140, HALF, "شیت متن هست؛ پنل سه‌بعدی نه")
rule(1141, MISSING, "پنل متریال")
rule(1142, MISSING, "پنل جلوهٔ ویژه")
rule(1143, OUT_OF_SCOPE, "پنل انیمیشن")
rule([1144, 1145], DONE, "ژست دو و سه انگشتی روی بوم، و دکمه در نوار بالا")
rule(1146, DONE, "دستگیره‌های تبدیل همیشه روی لایهٔ انتخاب‌شده‌اند")
rule(1147, DONE, "دکمهٔ کپی در نوار متنی")
rule(1148, MISSING, "ادغام با پایین")
rule([1149, 1150], MISSING, "کپی و پیست")
rule([1151, 1152], DONE, "دکمهٔ گروه و بازکردن در پنل لایه")
rule([1153, 1154], DONE, "`CanvasGesture.Undo` و `Redo`")
rule([1155, 1156], DONE, "همان")
rule([1157, 1158], DONE, "همان")
rule(1159, MISSING, "منوی سریع")
rule(1160, OUT_OF_SCOPE, "میانبر وب")
rule(1161, DONE, "زوم با دو انگشت")
rule(1162, MISSING, "چرخش سوژهٔ سه‌بعدی")
rule((1163, 1166), OUT_OF_SCOPE, "اتوماسیون دسکتاپ")
rule((1167, 1170), OUT_OF_SCOPE, "چاپ و اتصال به سرویس‌ها")
rule([1171, 1172], DONE, "`.pxl` را می‌شود جابه‌جا کرد و دوباره باز کرد")
rule((1173, 1175), OUT_OF_SCOPE, "شبکهٔ اجتماعی")
rule([1176, 1177], MISSING, "اشتراک و واردات پریست قلم‌مو")
rule([1178, 1179], OUT_OF_SCOPE, "لینک قالب ابری")
rule(1180, DONE, "`StylePreset`")
rule(1181, MISSING, "اعمال پریست روی چند عکس")
rule([1182, 1183], DONE, "ذخیره و بازکردن پروژه")
rule([1184, 1185], MISSING, "خط‌کش و شمارشگر")
rule(1186, MISSING, "QR")
rule(1187, OUT_OF_SCOPE, "ساخت وب‌سایت")
rule((1188, 1193), MISSING, "قطره‌چکان از روی بوم — **در هیچ‌کدام از اپ‌ها اختیاری نیست و ما نداریم**")
rule(1194, DONE, "`ControlSource.PRESSURE`")
rule(1195, OUT_OF_SCOPE, "نسخهٔ وب")
rule((1196, 1201), DONE, "رویداد فشار و شیب از `MotionEvent` خوانده می‌شود")
rule(1202, HALF, "`Geometry3D` در مدل هست، رندرکننده نیست")
rule((1203, 1210), OUT_OF_SCOPE, "ویدیو و انیمیشن — به‌خواست شما بیرون از دامنه")
rule([1211, 1212], DONE, "PSD و PSB — خواندن و نوشتن، با اعتبارسنجی روی هشت فایل تجاری")
rule(1213, DONE, "TIFF")
rule([1214, 1215, 1216, 1217], DONE, "JPEG، PNG، GIF و BMP")
rule(1218, MISSING, "RAW — به LibRaw روی NDK نیاز دارد")
rule([1219, 1220], MISSING, "PDF")
rule([1221, 1222], DONE, "")
rule([1223, 1224], OUT_OF_SCOPE, "ویدیو و GIF متحرک")
rule(1225, OUT_OF_SCOPE, "PowerPoint")
rule(1226, DONE, "`.pxl` معادل آن است")
rule([1227, 1228, 1229], DONE, "")
rule(1230, DONE, "`.pxl`")
rule([1231, 1232], DONE, "")
rule([1233, 1234], OUT_OF_SCOPE, "ویدیو")
rule(1235, DONE, "`.pxl`")
rule([1236, 1237, 1238], DONE, "")
rule([1239, 1240], OUT_OF_SCOPE, "انیمیشن")
rule([1241, 1242, 1243], DONE, "PNG شفاف، JPG و WebP")
rule(1244, MISSING, "PDF")
rule([1245, 1246], DONE, "")
rule([1247, 1248], OUT_OF_SCOPE, "ویدیو و GIF متحرک")
rule([1249, 1250], DONE, "")
rule((1251, 1255), MISSING, "فضای کاری قابل تعویض — یک فضای کاری داریم")
rule((1256, 1258), OUT_OF_SCOPE, "وایت‌برد و سند")
rule(1259, DONE, "تک بوم — همان انتخاب")
rule(1260, DONE, "")
rule(1261, OUT_OF_SCOPE, "ویرایش ویدیو")
rule(1262, DONE, "قلم‌مو روی لایهٔ نقاشی")
rule(1263, DONE, "")
rule(1264, OUT_OF_SCOPE, "انیمیشن")
rule([1265, 1266], DONE, "تک تصویر؛ دسته‌ای نیست")
rule(1266, MISSING, "ویرایش دسته‌ای")
rule([1267, 1268], HALF, "ترمیم هست؛ فضای کاری آرایش نیست")
rule([1269, 1270], MISSING, "فضای کاری سه‌بعدی و انیمیشن")
rule(1271, MISSING, "چفت‌شدن به شبکه")
rule(1272, MISSING, "چفت‌شدن به خط راهنمای دستی")
rule(1273, DONE, "`SnapEngine` به لبه و مرکز لایه‌های دیگر می‌چسبد")
rule(1274, DONE, "چفت‌شدن به لبهٔ بوم")
rule([1275, 1276], DONE, "خطوط راهنمای هوشمند زنده")
rule((1277, 1279), MISSING, "شبکه و تقارن")
rule(1280, MISSING, "تراز خودکار در مرکز")
rule(1281, MISSING, "چفت‌شدن به چهره")
rule(1282, MISSING, "شبکهٔ سه‌بعدی")
rule((1283, 1290), MISSING, "خط‌کش و شبکهٔ نمایشی — **هیچ‌کدام نیست**")
rule((1291, 1301), MISSING, "خط راهنمای دستی و نمایش/اختفای شبکه")
rule(1302, MISSING, "چند تخته‌کار")
rule(1303, MISSING, "چند صفحه در یک سند")
rule([1304, 1305], DONE, "تک بوم")
rule(1306, MISSING, "چند بوم در یک پروژه")
rule((1307, 1309), DONE, "تک بوم")
rule((1310, 1312), MISSING, "خروجی چند تخته‌کار")
rule(1313, HALF, "ماسک وکتوری همان کار را می‌کند")
rule((1314, 1319), HALF, "ماسک وکتوری؛ گالری قاب آماده نیست")
rule(1320, DONE, "`clipped` — گروه برش به‌صورت بازه در فهرست")
rule(1321, HALF, "ماسک وکتوری")
rule(1322, DONE, "ما ماسک برش کامل داریم — این ردیف دربارهٔ کمبودِ PixelLab است")
rule(1323, DONE, "ماسک رستری و وکتوری")
rule(1324, DONE, "")
rule([1325, 1326], DONE, "برش داریم")
rule(1327, DONE, "ماسک روی هر لایه‌ای")
rule(1328, DONE, "چهارده افکت، به‌صورت فهرست مرتب و تکرارشدنی")
rule(1329, DONE, "")
rule(1330, DONE, "سایه، حاشیه و برجستگی")
rule(1331, DONE, "افکت روی هر لایه‌ای، از جمله گروه")
rule(1332, DONE, "")
rule(1333, HALF, "`Effect.Reflection` هست؛ سایهٔ زمینی نه")
rule(1334, DONE, "افکت روی لایه، و لایهٔ تنظیم روی همه‌چیز زیرش")
rule(1335, HALF, "به PBR نیاز دارد")
rule(1336, DONE, "`Layer.Instance` — ویرایش یک‌بار، به‌روزرسانی همه‌جا")
rule((1337, 1343), DONE, "ما داریم — این ردیف‌ها دربارهٔ نداشتنِ اپ‌های دیگرند")
rule(1344, DONE, "چهارده لایهٔ تنظیم")
rule((1345, 1351), DONE, "لایهٔ تنظیم روی هر لایه یا کل سند")
rule((1352, 1359), DONE, "ویرایش غیرمخرب: افکت، ماسک و لایهٔ تنظیم، همه زندهٔ زنده")
rule(1360, DONE, "۵۰ مرحله")
rule(1361, MISSING, "تاریخچهٔ نسخهٔ پروژه")
rule((1362, 1367), DONE, "undo/redo با تاریخچهٔ درهم‌بافته")
rule([1368, 1369], HALF, "ذخیره هست؛ «ذخیره به نام» و «ذخیرهٔ یک کپی» جدا نیستند")
rule(1370, DONE, "")
rule(1371, DONE, "")
rule(1372, HALF, "ذخیره در گالری هست؛ اشتراک مستقیم نه")
rule([1373, 1374], DONE, "")
rule(1375, DONE, "")
rule(1376, HALF, "")
rule([1377, 1378], DONE, "")
rule(1379, DONE, "")
rule(1380, HALF, "")
rule(1381, DONE, "")
rule(1382, HALF, "")
rule([1383, 1384], DONE, "")
rule(1385, MISSING, "پیوند دادن لایه‌ها به هم")
rule((1386, 1392), DONE, "گروه‌بندی")
rule((1393, 1400), MISSING, "ترازبندی — **هیچ‌کدام نیست**")
rule((1401, 1408), MISSING, "توزیع — **هیچ‌کدام نیست**")
rule((1409, 1416), DONE, "خروجی و ذخیرهٔ یک‌ضربه‌ای در نوار بالا")
rule(1417, OUT_OF_SCOPE, "صفحه‌کلید دسکتاپ")
rule(1418, OUT_OF_SCOPE, "")
rule((1419, 1424), DONE, "`Gestures` — تک‌ضربه، دوضربه، نگه‌داشتن، کشیدن، چند‌لمسی")
rule((1425, 1432), HALF, "«اندازهٔ صفحه» دوربین را بازنشانی می‌کند؛ بازنشانی تنظیمات و ویرایش‌ها نه")
rule((1433, 1440), MISSING, "صفحهٔ تنظیمات برنامه — اصلاً نداریم")
rule((1441, 1448), HALF, "بودجهٔ حافظه هست و پیش از رندر بررسی می‌شود؛ صفحهٔ تنظیمش نیست")
rule((1449, 1456), HALF, "فقط فارسی")
rule((1457, 1464), MISSING, "راهنما و آموزش درون‌برنامه‌ای")
rule((1465, 1472), DONE, "هدف: اسنپدراگون ۸+ نسل ۱، اندروید ۸ به بالا، کاملاً آفلاین")
rule((1473, 1480), DONE, "رایگان و منبع‌باز — هیچ‌چیزی پشت پرداخت نیست")
rule((1481, 1488), DONE, "هدف: تایپوگرافی فارسی و طراحی کاور روی موبایل")
rule((1489, 1496), DONE, "یادگیری: رابط تک‌دستی با شیت‌های موضوعی")
rule((1497, 1500), DONE, "پلتفرم: اندروید ۸ به بالا")

# ─────────────────────────────────────────────────────────────────── generate
# ───────────────────────────────────────────────────────────── refresh, waves 10–38
#
# Everything below is a correction to a rule above, applied last so it wins. Kept as its own block
# rather than edited in place so the *movement* is legible: this is what twenty-eight waves closed,
# and re-reading it is how the next refresh knows where to look.
#
# Every flip here was checked with rg against the current tree, and against `app/android` or a
# `*Sheet.kt` specifically — a tick means a user can press something.

# Wave 9–12: the filter set, and the three adjustments that were missing.
rule([66], DONE, "`LensBlur` → `PixelFilters.lens` → «محو لنزی» در شیت فیلتر")
rule([68], DONE, "`MotionBlur` → `PixelFilters.motion` → «محو حرکتی» در شیت فیلتر")
rule([71], DONE, "`Blur.bilateral` → `PixelFilters.surface` → «محو سطحی» با شعاع و آستانه")
rule([72], DONE, "`Stylise.noise` → «افزودن دانه»، تک‌رنگ یا رنگی")
rule([73, 75], HALF, "موتور میانه‌گیری داخل `Despeckle`/`dustAndScratches` هست؛ کنترل مستقل ندارد")
rule([74], DONE, "`Denoise.dustAndScratches` → «گرد و غبار و خط»")
rule([76], DONE, "`Denoise.reduceNoise` → «کاهش نویز» با سه اسلایدر")
rule([111], DONE, "`Adjustment.ChannelMixer` + «میکسر کانال» در شیت تنظیم‌ها")
rule([121], DONE, "`Adjustment.SelectiveColor` — نه خانواده، نسبی و مطلق")
rule([125], DONE, "`Adjustment.Equalize` با هیستوگرام تجمعی منجمدشده و دکمهٔ اندازه‌گیری")
rule([132], DONE, "`Adjustment.ShadowsHighlights` — دو شعاع، دو گستره، رنگ و برش")
rule([341, 481], DONE, "`Stylise.pixelate` و `Stylise.vignette` در شیت فیلتر")

# Wave 10: arrange — the audit's own biggest hole, closed end to end.
rule([139, 140, 313, 402], DONE, "`EditorViewModel.pickColor` با میانگین ۵×۵ روی بوم")
rule([185, 186, 187, 393], DONE, "`mergeDown`/`mergeVisible`/`rasterize` — ساختار در ادیتور، پیکسل از GL")
rule([191, 192, 193], DONE, "`Editor.rotateCanvas(quarterTurns)`")
rule([315, 316, 385, 487], DONE, "`Editor.flipLayer` با مقیاس منفی — «قرینهٔ افقی/عمودی» در شیت چیدمان")
rule([317, 412, 413], DONE, "`alignLayers` و `distributeLayers` — توزیع فاصله‌ها، نه مرکزها")

# Wave 11: grid, ruler, guides.
rule([418], DONE, "`GridSpec` روی بوم، با گام وابسته به زوم")
rule([141], MISSING, "خط‌کشِ *ابزار* (اندازه‌گیری فاصله و زاویه)؛ نوارِ خط‌کش و راهنما هست")

# Wave 13: the panels whose models were finished and whose interfaces were not.
rule([236], DONE, "`GradientEditorBody` — توقف، میان‌نقطه و پیش‌نمایش از همان جدول رندر")
rule([242], DONE, "`HistogramView`، هم در شیت فیلتر و هم داخل سطوح و منحنی‌ها")
rule([244, 245], DONE, "`TypeSheet` — بخش «نویسه» و بخش «بند»، به‌علاوهٔ کشیده و محورها")

# Wave 14 and after: the PBR path.
rule([363], DONE, "`Pbr.shade` با GGX و محیط تولیدشده → `TextTo3D` → شیت سه‌بعدی")
rule([366, 367, 368], DONE, "چرخش روی هر سه محور در `Geometry3D.rotation`، از شیت سه‌بعدی")
rule([443], DONE, "`Material.metallic` — فلز واقعی، نه گرادیانِ شبیه فلز")

# Waves 36–38: the transforms the model promised and nothing drew.
rule([199], DONE, "`Transform.skew` — در ماتریس ترکیب‌کننده و در دستگیره‌ها، با ورودی عددی")
rule([201, 373, 488], DONE, "`Transform.perspective` — هوموگرافی واقعی، با تقسیم بر w در هر دو شیدر")
rule([200], HALF, "مدل چهار گوشهٔ آزاد را می‌پذیرد و رندر می‌کند؛ رابط فعلاً فقط حالت قرینه را می‌دهد")

# Colour lookup, which was renderable and unpointable.
rule([466], HALF, "`CubeLut` فایل `.cube` را می‌خواند و لایهٔ جدول رنگ به آن وصل است؛ خودِ پریست‌ها نیست")

# Section 9 restates the same capabilities per app, so the same evidence settles these too.
rule([991, 992, 993, 994, 995, 996, 997, 998], DONE, "`alignLayers` و `distributeLayers` در شیت چیدمان")
rule([1148], DONE, "`mergeDown` — از شیت چیدمان، بی‌میانبر صفحه‌کلید چون اپ لمسی است")
rule([1188, 1189, 1190, 1191, 1192, 1193], DONE, "`EditorViewModel.pickColor` با میانگین ۵×۵")
rule([966], DONE, "`Stylise.vignette` → «اعمال وینیت»")
rule([1004], DONE, "`ColorSettings.precision` حالا از شیت بوم انتخاب می‌شود — ۸، ۱۶، ۳۲ بیت")
rule([1039], DONE, "`Transform.perspective` — هوموگرافی واقعی روی هر لایه")
rule([1070, 1162], DONE, "چرخش سه‌بعدی روی سه محور از شیت سه‌بعدی")
rule([1102, 1103], DONE, "`TypeSheet` — «نویسه» و «بند»")
rule([1131], DONE, "`SettingsSheetBody`، از چرخ‌دندهٔ نوار بالا")
rule([1140, 1141], DONE, "`DimensionalSheetBody` با `MaterialControls` برای چهره، پخ و کناره")
rule([1271, 1272], DONE, "`SnapEngine` — `Kind.GRID` و `Kind.GUIDE`، با رتبهٔ چفت‌شدن")
rule([1277, 1278], DONE, "`SnapEngine.Kind.GRID`")
rule([951], DONE, "`Material.unlit` — سطحی که رنگ خودش را نگه می‌دارد، یعنی حاشیه روی حجم سه‌بعدی")
rule([965], HALF, "بیست‌ودو تنظیم روی لایه هست و `Adjustment.ColorLookup` جدول می‌خواند؛ لایهٔ تنظیم روی کل سند نه")

# ────────────────────────────── Pathfinder, which was there all along and had no test
#
# A second claim of mine that was wrong, the same shape as the LensBlur one: `PathOperation` has been
# wired to Skia's `Path.op` since wave 6 and reachable from the vector sheet. What was missing was a
# test that the operations return the right *region* — so `core:vector` now carries an independent
# implementation as the oracle, and the two are cross-checked on coverage.
# ──────────────────────────────────────── the six brushes that read instead of painting
rule([16], DONE, "`BrushMode.BLUR` — همان موتور قلم‌مو، با ماسک پوششِ ضربه به‌جای رنگ")
rule([17], DONE, "`BrushMode.SHARPEN`")
rule([18], DONE, "`BrushMode.SMUDGE` — تنها حالتی که به مسیر نیاز دارد نه ماسک")
rule([19], DONE, "`BrushMode.DODGE` با محدودهٔ تن و «حفظ رنگ»")
rule([20], DONE, "`BrushMode.BURN` — همان تابع با علامت منفی")
rule([21], DONE, "`BrushMode.SPONGE` با محافظتِ طراوت‌گونه از رنگ‌های اشباع")

# ─────────────────────────────────────── the face model, which was a decision and is now made
#
# The user's answer to "this needs a model you have to supply" was: download it yourself. So it is
# downloaded — MediaPipe's face_landmarker.task, Apache 2.0, 3.7 MB, bundled in the APK and running
# entirely on the device. docs/licenses/README.md records why that does not contradict the offline
# rule: nothing about a detection leaves the phone.
#
# Everything below was blocked on exactly that and on nothing else. The pixel operations already
# existed; what was missing was knowing where a lip was.
rule([460], DONE, "`FaceRetouch.tint` روی ماسک لب/گونه/پلک/ابرو — رنگ روی بافت خودِ عکس می‌نشیند")
rule([461], DONE, "`FaceRetouch.whiten` روی ماسک داخل دهان — اول اشباع‌زدایی، بعد روشنایی")
rule([462], DONE, "`FaceRetouch.removeRedEye` — مردمک را داخل ماسک چشم پیدا می‌کند")
rule((757, 758), DONE, "سفید کردن دندان با لغزندهٔ شدت، در شیت پرتره")
rule((759, 760), DONE, "`FaceRetouch.brighten` و `FaceReshape.Adjustment.EYES`")
rule((762, 766), DONE, "لاغری صورت، خط فک، گونه، بینی — `FaceReshape` با نقاط مهارشده")
rule(767, HALF, "حجم مو به ماسک مو نیاز دارد که مدل چهره نمی‌دهد")
rule(768, HALF, "خط رویش مو — همان")
rule((773, 782), DONE, "آرایش دیجیتال روی ماسک‌های `FaceRegion`، با شفافیتِ جدا برای هر کدام")
rule(799, DONE, "`FaceRetouch.removeRedEye`")
rule((820, 821), DONE, "`FaceRetouch.reduceShine` و نرمی پوستِ محدود به ماسکِ پوست")
rule((831, 832), HALF, "فرم دندان و لبخند به مش دندان نیاز دارند، نه نقاط چهره")
rule((833, 835), HALF, "گردن، شانه و قد بیرون از مشِ چهره‌اند — با `Liquify` دستی شدنی")
rule(836, HALF, "عضله — همان")
rule(837, DONE, "`FaceRetouch.reduceShine` رنگ پوست را به میانگینِ خودِ همان صورت می‌برد")
rule([843, 844], HALF, "همهٔ اجزایش هست و با یک پیش‌فرض جمع می‌شود؛ دکمهٔ «یک‌لمسی» هنوز نه")
rule(1076, DONE, "شیت پرتره — تشخیص، آرایش، دندان، چشم، تغییر شکل")

# ───────────────────────────────────────────────── Hypic, from sixteen screenshots
#
# A naming collision worth writing down: section 5 is headed "های پیک (HiPaint)" and its hundred
# rows describe HiPaint, the sketching app — watercolour brushes, symmetry, a floating reference
# window. The app the user means by that name is *Hypic*, a photo editor, and it has no section in
# this document at all. Its inventory is docs/REFERENCE-HYPIC.md until rows are written for it.
#
# Three of its adjustments were things we genuinely lacked, and all three are now built. They land
# on section 9's technical rows because that is where this list keeps its filter entries.
rule([484], DONE, "`LocalContrast.Scale.CLARITY` — کنتراست موضعی روی روشنایی، از شیت فیلتر")
rule([118], DONE, "`Adjustment.HueSaturation` با `range` — «همه» و شش خانوادهٔ رنگ، مثل خودِ فتوشاپ")
rule([868], DONE, "`LightRays` — پرتوهای پراکنده از یک نقطه، با میرایی در طول پرتو")

# ───────────────────────────────────────────── AirBrush, re-read against thirty screenshots
#
# Section 7 was written from store copy and was the weakest in the document — the screenshots
# (inventoried in docs/REFERENCE-AIRBRUSH.md) both corrected stale rows and found real gaps that no
# feature list names, because they are about layout rather than capability.
rule(791, DONE, "`PixelFilters.vignette` از شیت فیلتر — این ردیف کهنه بود")
rule(795, DONE, "«قرینهٔ افقی» و «قرینهٔ عمودی» در شیت چیدمان — این ردیف کهنه بود")
rule(793, DONE, "`AspectRatio.PRESETS` در شیت بوم — ۱:۱، ۴:۵، ۹:۱۶ و بقیه، با قابِ ثابت‌نسبت روی بوم")
rule(794, DONE, "چرخش لایه با ورودی عددی؛ چرخش ۹۰ درجه و قرینه از شیت چیدمان")
rule(804, DONE, "`HeldBarIcon` کنار واگرد — نگه دار تا اولِ کار را ببینی، ول کن تا برگردد")
# What the screenshots showed that the list did not.
rule(802, DONE, "`LensBlur` با پرهٔ دیافراگم (۵، ۶، ۸) و وزن‌دهی هایلایت، از شیت فیلتر")
rule(801, DONE, "`GradientBlur.Shape.LINEAR` — تیلت‌شیفت، از شیت فیلتر؛ `RADIAL` بوکهٔ پرتره")
rule([805, 806], MISSING, "ذخیرهٔ «لوک» از تنظیم‌های فعلی و زدنش روی عکس بعدی — `StylePreset` هست، معادلِ تصویری‌اش نه")
rule(783, HALF, "`CubeLut` فایل `.cube` را می‌خواند و لایهٔ جدول رنگ به آن وصل است؛ شبکهٔ بندانگشتیِ زنده و خودِ لوک‌ها نیست")


lines = open(SRC, encoding="utf-8").read().splitlines()
items = {}
order = []
section_of = {}
current = None
SECTION_RE = re.compile(r"^\[بخش\s*(.+?)\]$")
ITEM_RE = re.compile(r"^(\d+)\.\s*(.+)$")

for line in lines:
    line = line.strip()
    m = SECTION_RE.match(line)
    if m:
        current = m.group(1)
        continue
    m = ITEM_RE.match(line)
    if m:
        n = int(m.group(1))
        if n in items:
            continue
        items[n] = m.group(2).strip()
        order.append(n)
        section_of[n] = current or "—"

status = {}
notes = {}
for nums, st, note in RULES:
    for n in nums:
        if n in items:
            status[n] = st
            notes[n] = note

missing_rule = [n for n in order if n not in status]
if missing_rule:
    print("NO RULE FOR:", missing_rule[:40], "count", len(missing_rule), file=sys.stderr)
    sys.exit(1)

counts = collections.Counter(status[n] for n in order)
per_section = collections.OrderedDict()
for n in order:
    per_section.setdefault(section_of[n], collections.Counter())[status[n]] += 1

LABEL = {
    DONE: "هست",
    HALF: "نیمه",
    MISSING: "نیست",
    OUT_OF_SCOPE: "خارج از دامنه",
}

out = []
w = out.append
w("# ممیزی ۱۵۰۰ ویژگی")
w("")
w("فهرستی که فرستادید، مورد به مورد، در برابر کدی که واقعاً در این مخزن هست.")
w("")
w("## روش")
w("")
w("هر ردیف در برابر کد بررسی شده، نه در برابر حافظه یا حدس. جایی که قابلیت در **مدل**")
w("هست ولی هیچ چیزی روی صفحه به آن نمی‌رسد، وضعیت «نیمه» است نه «هست» — همین تفکیک")
w("همان چیزی است که شما درست گرفتید: مدل داشتن با داشتنِ ابزار یکی نیست.")
w("")
w("| نشانه | معنی |")
w("|---|---|")
w(f"| {DONE} | هست و از رابط کاربری در دسترس است |")
w(f"| {HALF} | نیمه — یا مدلش هست و رابط ندارد، یا با دو-سه گام دیگر شدنی است |")
w(f"| {MISSING} | نیست |")
w(f"| {OUT_OF_SCOPE} | عمداً بیرون از دامنه: ویدیو، ابر، شبکهٔ اجتماعی، یا مدل هوش مصنوعی سروری |")
w("")
w("«خارج از دامنه» تصمیم خودتان است، نه کمبود: ویدیو را گفتید نباشد، و گفتید همه‌چیز تا")
w("حد امکان بدون هوش مصنوعی و آفلاین باشد.")
w("")
# These two paragraphs were hand-written into the markdown after it was generated, which meant the
# next run of this script would have silently deleted them. Emitting them from here is the only
# arrangement in which the document and its generator cannot disagree.
w("یک نکته دربارهٔ خودِ فهرست: عنوان هر بخش عددی می‌گوید که با تعداد ردیف‌های شماره‌دارِ")
w("همان بخش نمی‌خواند — مثلاً عنوان کنوا «۲۰۰ ویژگی» است ولی ردیف‌های ۲۵۱ تا ۳۵۰ صد")
w("تاست. جمع کل واقعاً ۱۵۰۰ است و همه‌شان اینجا آمده‌اند؛ فقط توزیعشان بین بخش‌ها با")
w("عنوان‌ها فرق دارد. ستون «جمع» در جدول زیر، شمارش واقعی است.")
w("")
w("بخش نهم هم بیشترش تکرارِ همان ردیف‌های قبلی است، منتها به تفکیک هر اپ — پس درصدِ")
w("کلی را کمی به سمت بالا می‌کشد. عددی که به آن نگاه می‌کنم بخش‌های یک تا هشت است.")
w("")
w("## جمع کل")
w("")
w("| وضعیت | تعداد | درصد |")
w("|---|---:|---:|")
total = len(order)
for st in (DONE, HALF, MISSING, OUT_OF_SCOPE):
    c = counts[st]
    w(f"| {st} {LABEL[st]} | {c} | {c * 100 // total}٪ |")
w(f"| **جمع** | **{total}** | |")
w("")
inscope = total - counts[OUT_OF_SCOPE]
w(f"از {inscope} موردی که در دامنه‌اند، {counts[DONE]} تا هست، {counts[HALF]} تا نیمه و")
w(f"{counts[MISSING]} تا نیست — یعنی حدود {(counts[DONE] + counts[HALF]) * 100 // inscope}٪ دامنه")
w("دست‌کم تا نیمه پوشیده است.")
w("")
w("## به تفکیک بخش")
w("")
w("| بخش | ✅ | 🟡 | ❌ | ⛔ | جمع |")
w("|---|---:|---:|---:|---:|---:|")
for sec, c in per_section.items():
    tot = sum(c.values())
    w(f"| {sec} | {c[DONE]} | {c[HALF]} | {c[MISSING]} | {c[OUT_OF_SCOPE]} | {tot} |")
w("")

last_section = None
for n in order:
    if section_of[n] != last_section:
        last_section = section_of[n]
        w("")
        w(f"## {last_section}")
        w("")
        w("| # | ویژگی | وضعیت | توضیح |")
        w("|---:|---|:--:|---|")
    note = notes[n].replace("|", "\\|")
    w(f"| {n} | {items[n]} | {status[n]} | {note} |")

w("")
w("## چه چیزی از بیرون لازم است")
w("")
w("بیشترِ «نیست»ها کار کد است نه کار دارایی، و خودم می‌سازمشان. این‌ها آن‌هایی هستند")
w("که بدون چیزی از بیرون ساخته نمی‌شوند:")
w("")
w("| مورد | چه چیزی لازم است |")
w("|---|---|")
w("| رمزگشایی RAW | کتابخانهٔ LibRaw روی NDK — پروانه‌اش LGPL/CDDL است و باید تصمیم بگیرید |")
w("| قلم‌موهای بافتی (آبرنگ، زغال، پاستل) | تصویر نوک قلم‌مو؛ یا فایل ABR فتوشاپ که خواننده‌اش را می‌نویسم |")
w("| استیکر، آیکون و تزئینات | مجموعهٔ گرافیکی با پروانهٔ آزاد |")
w("| قالب‌های آماده (رزومه، منو، گواهی) | طرح‌هایی که خودتان بپسندید — من ساختارش را می‌سازم |")
w("| متریال سه‌بعدی (فلز، شیشه، چوب) | نقشهٔ محیطی HDR و بافت — یا بگویید تولیدشان کنم |")
w("| فیلترهای رنگی آماده | فایل‌های LUT (`.cube`) — خواننده‌اش هست، خودِ LUTها نیست |")
w("")
w("### فهرست قبلی، که تمام شد")
w("")
w("نُه موردی که این سند در نسخهٔ اولش به‌عنوان اولویت نوشته بود — ترازبندی و توزیع، قطره‌چکان،")
w("ادغام و تخت‌کردن، خط‌کش و شبکه و راهنما، چرخش بوم و قرینه‌سازی و ورودی عددی، پنل کاراکتر و")
w("پاراگراف، ویرایشگر گرادیان، محو حرکتی و وینیت و پیکسلی‌کردن، و رندرکنندهٔ PBR — **هر نُه‌تا")
w("ساخته شدند.** موج‌های ۱۰ تا ۳۸.")
w("")
w("و از فهرستِ بازنگریِ همین چند روز: **تأیید/انصراف صریح روی هر شیت** (سرِ هر شیت حالا")
w("✕ و ✓ دارد و انصراف سند را به لحظهٔ باز شدنِ شیت برمی‌گرداند)، **نقشهٔ محیطی HDR** (`LatLong` — عکس واقعیِ یک مکان،")
w("با زنجیرهٔ میپِ پیش‌فیلترشده برای زبری)، **محو سطحی**، **جدول رنگ با فایل `.cube`**،")
w("**ویرایشگر گرادیان روی نقشهٔ گرادیان**، **عمق بیت**، **اریب و پرسپکتیو**، و از سی تصویرِ")
w("ایربراش: **برش با نسبت‌های آماده** و **مقایسهٔ قبل و بعد**.")
w("")
w("### آنچه حالا مانده، به ترتیب")
w("")
w("**اول، دستهٔ «هست ولی سیم‌کشی ندارد».** ارزان‌ترین بردها، و همان دسته‌ای که این مخزن بارها")
w("در آن گیر افتاده: مدل یا الگوریتم تمام است و هیچ کنترلی به آن نمی‌رسد، که از نداشتن بدتر")
w("است چون از بیرون شبیه داشتن به نظر می‌رسد.")
w("")
w("1. **اعوجاج آزاد (Distort)** — موتورش همان هوموگرافی پرسپکتیو است و کار می‌کند؛ فقط رابطِ")
w("   کشیدن چهار گوشه ندارد و اسلایدر فعلی حالت قرینه را می‌دهد.")
w("2. **رمزگشایی RAW** — به تصمیم شما دربارهٔ پروانهٔ LibRaw نیاز دارد.")
w("")
w("**دوم، آنچه واقعاً نیست و کدش را خودم می‌نویسم:**")
w("")
w("3. **جفت رنگ پیش‌زمینه/پس‌زمینه** — اصلاً در مدل نیست، و نیمی از رفتار ابزارهای فتوشاپ")
w("   فرضش را می‌کند.")
w("4. **قلم‌موهای روشن‌کننده، تیره‌کننده، انگشتی و اسفنجی** — موتور قلم‌مو هست؛ این‌ها حالت")
w("   ابزارند نه زیرسیستم تازه.")
w("5. **گالری فیلترهای هنری** — رنگ روغن، آبرنگ، مداد رنگی، بلوری.")
w("6. **گالری محو** — میدانی، عنبیه‌ای، تیلت‌شیفت، مسیری، و **شکل دیافراگم** که بوکه را از")
w("   محو ساده جدا می‌کند.")
w("7. **انتخاب سریع، ماسک سریع، پاک‌کن پس‌زمینه، متن عمداً عمودی.**")
w("8. **پریست فیلتر و لوک** — ساختارش هست (`.cube` خوانده می‌شود، `StylePreset` هست)؛ خودِ")
w("   مجموعه نیست، و شبکهٔ بندانگشتیِ زنده روی عکسِ خودِ کاربر هم نیست.")
w("")
w("جزئیات صفحه‌به‌صفحهٔ ایربراش در `docs/REFERENCE-AIRBRUSH.md` است.")
w("")

open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"{total} items → {OUT}")
print("  ".join(f"{LABEL[s]}={counts[s]}" for s in (DONE, HALF, MISSING, OUT_OF_SCOPE)))
